import type { Metadata } from "next";
import "./globals.css";

import LogoutWrapper from "@/components/LogoutWrapper";
import SessionProviderWrapper from "@/components/SessionProviderWrapper";

export const metadata: Metadata = {
  title: "Todo App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SessionProviderWrapper>
          <LogoutWrapper />
          {children}
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
