import type { Metadata } from "next";
import "./globals.css";

import LogoutWrapper from "@/components/LogoutWrapper";
import SessionProviderWrapper from "@/components/SessionProviderWrapper";

import initTranslations from "@/app/i18n";
import TranslationsProvider from "@/components/TranslationsProvider";
import { ReactNode } from "react";

export const metadata: Metadata = {
  title: "Todo App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: {
  children: ReactNode;
  params: { [key: string]: string };
}) {
  const { locale } = await params;
  const { resources } = await initTranslations(locale, ["common"]);
  return (
    <html>
      <body>
        <TranslationsProvider
          locale={locale}
          resources={resources}
          namespaces={["common"]}
        >
          <SessionProviderWrapper>
            <LogoutWrapper />
            {children}
          </SessionProviderWrapper>
        </TranslationsProvider>
      </body>
    </html>
  );
}
